import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

const geistSans = localFont({
  src: '../fonts/Geist-Regular.ttf',
  variable: '--font-geist-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
